/** Brand colors for language picker cards (OneCompiler-style tiles). */
export const LANGUAGE_BRAND: Record<string, { bg: string; fg: string; abbr: string }> = {
  python: { bg: "#3776ab", fg: "#ffd343", abbr: "Py" },
  java: { bg: "#f89820", fg: "#ffffff", abbr: "Jv" },
  c: { bg: "#00599c", fg: "#ffffff", abbr: "C" },
  cpp: { bg: "#00599c", fg: "#ffffff", abbr: "C+" },
  javascript: { bg: "#f7df1e", fg: "#000000", abbr: "JS" },
  lua: { bg: "#000080", fg: "#ffffff", abbr: "Lu" },
  php: { bg: "#777bb4", fg: "#ffffff", abbr: "PHP" },
  nodejs: { bg: "#339933", fg: "#ffffff", abbr: "Nd" },
  csharp: { bg: "#68217a", fg: "#ffffff", abbr: "C#" },
  assembly: { bg: "#6e4c13", fg: "#ffffff", abbr: "Asm" },
  bash: { bg: "#4eaa25", fg: "#ffffff", abbr: "Sh" },
  tkinter: { bg: "#3776ab", fg: "#ffffff", abbr: "Tk" },
  html: { bg: "#e44d26", fg: "#ffffff", abbr: "H5" },
  react: { bg: "#61dafb", fg: "#20232a", abbr: "Rx" },
  vue: { bg: "#42b883", fg: "#ffffff", abbr: "Vu" },
  angular: { bg: "#dd0031", fg: "#ffffff", abbr: "Ng" },
  bootstrap: { bg: "#7952b3", fg: "#ffffff", abbr: "Bs" },
  tailwind: { bg: "#06b6d4", fg: "#ffffff", abbr: "Tw" },
  jquery: { bg: "#0769ad", fg: "#ffffff", abbr: "JQ" },
  mysql: { bg: "#00758f", fg: "#f29111", abbr: "My" },
  postgresql: { bg: "#336791", fg: "#ffffff", abbr: "Pg" },
  mongodb: { bg: "#47a248", fg: "#ffffff", abbr: "Mg" },
  sqlite: { bg: "#003b57", fg: "#90cdf4", abbr: "Sq" },
  redis: { bg: "#d82c20", fg: "#ffffff", abbr: "Rd" },
  mariadb: { bg: "#003545", fg: "#c49a6c", abbr: "Ma" },
  plsql: { bg: "#f80000", fg: "#ffffff", abbr: "PL" },
  mssql: { bg: "#cc2927", fg: "#ffffff", abbr: "MS" },
  cassandra: { bg: "#1287b1", fg: "#ffffff", abbr: "Ca" },
  questdb: { bg: "#1c1c1c", fg: "#d4a72c", abbr: "Qd" },
  duckdb: { bg: "#fff000", fg: "#000000", abbr: "Dk" },
};
