/**
 * Python Full Stack — 6 months total.
 * Month 1–3 (Day 1–100): All basics and concepts. 2 hr/day = 1 hr theory + 1 hr practical.
 * Month 4–6: Training & real-time projects (no day count — applied work).
 * References: docs.python.org/3, postgresql.org/docs, docs.docker.com, CI/CD best practices.
 */

export interface IndexSection {
  title: string;
  days: string;
  items: string[];
  /** If set, clicking this section in the index jumps to the first slide with this title. */
  linkToTitle?: string;
  /** If set, clicking this section jumps to the first slide with this day (e.g. "Day 1"). */
  linkToDay?: string;
}

/** How we teach — 2hr/day, 1hr theory + 1hr practical. 6 months = 3 months concepts + 3 months projects. */
export const TEACHING_FORMAT_SECTION: IndexSection = {
  title: "How we teach — 2 hours daily | 6 months total",
  days: "Format",
  linkToTitle: "6 months total — 3 months concepts + 3 months projects",
  items: [
    "Month 1–3: Day 1 to Day 100 — all basics and concepts (theory + practical each day)",
    "Month 4–6: Training & real-time projects — no new concepts, only building and deploying",
    "1 hour THEORY + 1 hour PRACTICAL every day (references: Python, PostgreSQL, Docker, CI/CD docs)",
    "Every topic: explain clearly then build — no rush, full understanding",
  ],
};

/** Unique projects — built mainly in Month 4–6 (training phase). */
export const PROJECTS_SECTION: IndexSection = {
  title: "Projects we will build",
  days: "Month 4–6",
  linkToTitle: "Month 4–6: Training & projects",
  items: [
    "Project 1: Dev Diary — Blog with Django + PostgreSQL (posts, comments, auth, admin)",
    "Project 2: Task API — REST API for a task app (CRUD, filters, auth token, Postman)",
    "Project 3: Scrape It — Web scraping (extract data from a site, save to DB or CSV)",
    "Project 4: Chat App — Real-time chat with WebSockets + simple chatbot",
    "Project 5: Deploy It — Take a project to VPS (Gunicorn + Nginx + HTTPS)",
    "Project 6: Box It — Dockerize app + PostgreSQL + Nginx (docker-compose)",
    "Project 7: Pipeline — CI/CD with GitHub Actions (test on push → deploy to server)",
    "Project 8: Portfolio Full Stack — Your own site (Django + DB + deployed, for interviews)",
  ],
};

export const CURRICULUM_INDEX_DAYS: IndexSection[] = [
  PROJECTS_SECTION,
  {
    title: "Introduction — Why Python & the Internet",
    days: "Day 1–6",
    linkToTitle: "Installing Python",
    items: [
      "Installing Python (Python 3.x — see docs.python.org/3)",
      "Installing PyCharm / VS Code",
      "Why Python? Why full stack?",
      "Introduction to programming & Python",
      "How does the Internet work?",
      "Client, server, HTTP — high level",
      "First Python program — print, running scripts",
    ],
  },
  {
    title: "Python basics",
    days: "Day 7–14",
    items: [
      "Literals",
      "Variables",
      "Keywords",
      "Primitive datatypes — int, float, str, bool (Python Library reference)",
      "Basic operations with strings",
      "Type conversion — int, float, str",
      "Type conversion — boolean",
      "Arithmetic & assignment operators",
      "Comparison & logical operators",
      "Associativity & precedence of operators",
      "Printing to console — print()",
      "Taking input — input()",
      "f-strings and string formatting",
      "Virtual environment (venv) — isolate project dependencies",
      "pip — install packages (e.g. pip install django)",
      "Numeric functions, coding exercises",
    ],
  },
  {
    title: "Strings in Python",
    days: "Day 15–18",
    items: [
      "String indexing and slicing",
      "String methods — upper, lower, strip, split, join",
      "String formatting — %, .format(), f-strings",
      "Escape sequences",
      "Multiline strings",
      "String membership — in, not in",
      "Practice — string manipulation",
    ],
  },
  {
    title: "Control statements",
    days: "Day 19–21",
    items: [
      "if statement",
      "if-else",
      "if-elif-else",
      "Nested conditionals",
      "Conditional expressions (ternary)",
      "Coding exercises",
    ],
  },
  {
    title: "Loops",
    days: "Day 22–25",
    items: [
      "for loop — range(), iterating sequences",
      "while loop",
      "break and continue",
      "Nested loops",
      "else clause with loops",
      "Coding exercises",
    ],
  },
  {
    title: "Lists in Python",
    days: "Day 26–29",
    items: [
      "Creating lists",
      "List indexing and slicing",
      "List methods — append, extend, insert, remove, pop",
      "List comprehensions",
      "Nested lists",
      "Sorting and reversing",
      "Practice — lists",
    ],
  },
  {
    title: "Tuples, sets & dictionaries",
    days: "Day 30–35",
    items: [
      "Tuples — creation, indexing, unpacking",
      "When to use tuple vs list",
      "Sets — unique elements, add, remove",
      "Set operations — union, intersection, difference",
      "Dictionaries — keys, values, items",
      "Dictionary methods — get, keys, values, update",
      "Dictionary comprehensions",
      "Nested structures",
      "Practice — tuples, sets, dicts",
    ],
  },
  {
    title: "Functions & modules",
    days: "Day 36–42",
    items: [
      "Defining functions (Python Tutorial)",
      "Parameters and arguments",
      "Return values",
      "Default arguments",
      "*args and **kwargs",
      "Scope — local vs global",
      "Lambda functions",
      "Modules — import, from",
      "Packages and __init__.py",
      "Standard library — os, sys, math, datetime (Library reference)",
      "Practice — functions and modules",
    ],
  },
  {
    title: "File handling & exception handling",
    days: "Day 43–46",
    items: [
      "Opening files — open(), read, write",
      "with statement — context manager (Language reference)",
      "Reading line by line",
      "Writing to files",
      "try and except",
      "Multiple except blocks",
      "finally block",
      "Raising exceptions",
      "Custom exception classes",
      "Practice — files and exceptions",
    ],
  },
  {
    title: "Object oriented programming",
    days: "Day 47–55",
    items: [
      "Introduction to OOP",
      "What are classes and objects",
      "Creating classes and objects",
      "What are attributes",
      "Instance methods",
      "Arguments in instance methods",
      "__init__ and instance variables",
      "Class variables",
      "Class methods",
      "Static methods",
      "Inheritance — introduction and single inheritance",
      "Single inheritance and initialization",
      "Multiple and multilevel inheritance",
      "Introduction to polymorphism",
      "Polymorphism — operator overloading",
      "Polymorphism — method overloading and overriding",
      "Encapsulation and abstraction",
      "Abstract class",
      "Practice — OOP mini project",
    ],
  },
  {
    title: "HTTP basics & web intro",
    days: "Day 56–58",
    items: [
      "HTTP — URLs, methods (GET, POST)",
      "Status codes — 200, 404, 500",
      "Request and response headers",
      "Browser and server interaction",
      "Preparing for Django/Flask",
    ],
  },
  {
    title: "Django — fundamentals",
    days: "Day 59–65",
    items: [
      "Introduction to Django",
      "MVT — Model, View, Template",
      "Installing Django, creating project",
      "Apps — startapp, structure",
      "URL routing — urlpatterns",
      "Views — function-based views",
      "Templates — variables, filters, tags",
      "Template inheritance — extends, block",
      "Static files — CSS, JS, images",
      "First Hello World web page",
      "Passing data from view to template",
    ],
  },
  {
    title: "Django — forms & models",
    days: "Day 66–72",
    items: [
      "HTML forms — GET and POST",
      "Django forms — Form class",
      "Form validation",
      "ModelForm",
      "Introduction to databases",
      "Django ORM — defining models",
      "Fields — CharField, IntegerField, DateTimeField, ForeignKey",
      "Migrations — makemigrations, migrate",
      "Admin site — registering models",
      "CRUD with Django ORM — create, read, update, delete",
    ],
  },
  {
    title: "PostgreSQL — schema & SQL",
    days: "Day 73–78",
    items: [
      "Installing PostgreSQL (postgresql.org/docs)",
      "Schema design — tables, relations",
      "Primary key, foreign key",
      "Raw SQL — SELECT, WHERE, ORDER BY",
      "Raw SQL — INSERT, UPDATE, DELETE",
      "JOINs — INNER, LEFT, RIGHT",
      "Aggregations — COUNT, SUM, AVG",
      "Indexes — CREATE INDEX (when and why)",
      "Transactions — ACID, BEGIN, COMMIT, ROLLBACK",
      "EXPLAIN — understanding query plans",
      "Connecting Django to PostgreSQL",
      "Running raw SQL in Django",
      "Backup & restore — pg_dump, pg_restore",
      "Practice — schema and queries",
    ],
  },
  {
    title: "REST APIs with Django",
    days: "Day 79–84",
    items: [
      "REST — GET, POST, PUT, PATCH, DELETE",
      "JSON request and response",
      "Django REST framework intro",
      "Serializers",
      "ViewSets and Routers",
      "Authentication — session, token",
      "Permissions — IsAuthenticated, custom",
      "API endpoints — design and versioning",
      "Testing APIs — Postman / curl",
      "Unit tests with pytest — write and run tests",
      "Practice — build a REST API",
    ],
  },
  {
    title: "Frontend — HTML, CSS, JavaScript",
    days: "Day 85–88",
    items: [
      "HTML structure — tags, attributes",
      "CSS basics — selectors, box model",
      "CSS — layout, flexbox",
      "JavaScript — variables, functions",
      "DOM manipulation",
      "Fetch API — calling your backend",
      "Server-side templates — Django templates / Jinja2",
      "Forms and validation — frontend + backend",
    ],
  },
  {
    title: "Web scraping",
    days: "Day 89–90",
    items: [
      "What is web scraping — when and why",
      "requests — fetch HTML from URLs",
      "BeautifulSoup — parse HTML, find elements",
      "Extracting text, links, tables",
      "Saving data — CSV, JSON, or database",
      "Respectful scraping — robots.txt, rate limiting",
      "Practice — scrape a real site (e.g. listings, news)",
    ],
  },
  {
    title: "WebSockets & real-time — Chat app & chatbot",
    days: "Day 91–93",
    items: [
      "HTTP vs WebSockets — when to use each",
      "WebSocket basics — connect, send, receive",
      "Django Channels (or Flask-SocketIO) — real-time in Django",
      "Building a simple chat app — multiple users, rooms",
      "Chatbot — rule-based replies or API (e.g. simple Q&A)",
      "Integrating chatbot into chat app",
      "Practice — deploy a minimal chat app",
    ],
  },
  {
    title: "Git & Linux",
    days: "Day 94–95",
    items: [
      "Git — init, add, commit",
      "Branching — branch, checkout, merge",
      "Remote — origin, push, pull",
      "Collaboration — pull requests",
      "Linux command line — ls, cd, pwd, mkdir",
      "File system — permissions, chmod",
      "Processes — ps, kill",
      "Deployment concepts — server, domain, port",
    ],
  },
  {
    title: "Gunicorn, VPS & Nginx",
    days: "Day 96–98",
    items: [
      "Gunicorn — production WSGI server",
      "Running Django with Gunicorn",
      "VPS — choosing provider, SSH",
      "VPS setup — Linux, Python, PostgreSQL",
      "Nginx — reverse proxy",
      "Nginx config — proxy_pass, static files",
      "SSL/TLS — HTTPS with Let's Encrypt",
      "Deploying first real project",
      "Debugging deployment issues",
    ],
  },
  {
    title: "Docker",
    days: "Day 99",
    items: [
      "Containers — what and why (docs.docker.com)",
      "Dockerfile reference — FROM, COPY, RUN, CMD, ENTRYPOINT",
      ".dockerignore — keep images small",
      "Building and running images — docker build, docker run",
      "Docker Build overview",
      "docker-compose — app + PostgreSQL + Nginx",
      "Volumes and networks",
      "Multi-stage builds (optional)",
      "Same setup on dev and production",
    ],
  },
  {
    title: "CI/CD pipeline",
    days: "Day 100",
    items: [
      "CI (Continuous Integration) — build + test on every commit",
      "CD (Continuous Delivery) — deploy to staging; manual push to production",
      "Continuous Deployment — auto deploy to production after tests",
      "Pipeline: commit → build → test → notify → deploy to staging → production",
      "GitHub Actions / GitLab CI — write a pipeline",
      "Rollback strategy — how to revert a bad deploy",
      "Best practices — fast feedback, fix broken builds first",
      "Practice — full pipeline for your project",
    ],
  },
  {
    title: "Month 4–6: Training & real-time projects",
    days: "No day count",
    items: [
      "Build 2–3 full-stack projects end-to-end",
      "Code reviews — one-on-one mentorship",
      "Resume building",
      "LinkedIn and portfolio site",
      "Mock technical interviews",
      "Mock HR interviews",
      "Company patterns and negotiation",
      "Conclusion — you're job ready",
    ],
  },
];
